# Generated by Django 5.1.6 on 2025-08-19 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_formacion', models.CharField(max_length=100, verbose_name='Centro de Formación')),
                ('dierccion', models.CharField(max_length=200, verbose_name='Dirección del Centro de Formación')),
                ('horario_funcionamiento', models.CharField(max_length=100, verbose_name='Horario de Funcionamiento')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['centro_formacion'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('CAR', 'Carro'), ('MOT', 'Moto'), ('OTRO', 'Otro')], max_length=4, verbose_name='Tipo de vehículo')),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('color', models.CharField(choices=[('NEGRO', 'Negro'), ('AZUL', 'Azul'), ('GRIS', 'Gris'), ('BLANCO', 'Blanco'), ('ROJO', 'Rojo'), ('OTRO', 'Otro')], max_length=10)),
                ('marca', models.CharField(max_length=10, null=True, verbose_name='Marca del vehículo')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(null=True, verbose_name='observaciones en el vehículo')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructores.instructor', verbose_name='Propietario del vehículo (Instructor)')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=7, verbose_name='Tipo de movimiento')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del registro')),
                ('observaciones', models.TextField(null=True, verbose_name='Observaciones del registro')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
